# Scenario 1

#### Theoretical Data Source: Amsterdam availability data scraped from AirBnB on December 24th.

Question: What are the popular neighborhoods in Amsterdam?

Exceptional circumstances: the data was collected on Christmas Eve. The date of the collection would clearly influence the data in several ways. The number of AirBnB reservations may be significantly elevated due to the holiday. The location (neighborhood) of reservations may be affected by location of the customer's family, the time period in which they booked (early or late reservations), as well as the availablity of the customer's first(second, or third) choice. In addition, many AirBnB's which are availble for much of the year may not be available during the holiday when the owner may be in residence and hosting their own family rather than being available for an AirBnB reservation.

##### More accurate question: Which neighborhoods have the most AirBnB bookings during the Christmas season?

# Scenario 2

#### Theoretical Data Source: Mental health services use on September 12, 2001 in San Francisco, CA and New York City, NY.

Question: How do patterns of mental health service use vary between cities?

Exceptional circumstances: this data was collected one day after a national tragedy/emergency in the United States. It is very likely that ANY data collected in the United States, or even the world, would be affected by the event of 9/11/01.

The specific factors which would affect this particular data are:
1. New York City was directly impacted by the events of 9/11. Every single person living or visiting NYC on that day would have been directly impacted and thus may have sought Mental Health services. This, obviously, would not have been true on 9/10/01 or any date prior to that. 
2. It could be argued that the use of Mental Health services in NYC was permanently altered after 9/11. Many who may have never previously used or considered using Mental Health services may have used the services on that day. 
3. San Fransisco was the destination of one of the four highjacked flights involved in the events of 9/11. Many of the passengers on United flight 93 either lived in SF or surronding areas, had family/friends who lived there, or had business there. The impact of the loss of even one life in an event with global impact would ripple out to affect dozens if not hundreds of people, and may be argued to impact the use of Mental Health services in that area.

##### More accurate question: Incidence of Mental Health services use in cities impacted by national tragedy?
Reframe: if data is available before 9/12, could compare/contrast the useage of Mental Health services before & after

# Scenario 3

In [ ]:
#https://www.kaggle.com/erikhambardzumyan/pubs

#### Actual Data Source: Armenian Pub Survey.

Question: What are the most common reasons Armenians visit local pubs?

Description
The dataset collected from an online survey questionnaire includes behavioral, psychographic, geographic and demographic information about Armenian pubs.

The data has been intended for an independent project organized by the students of the American University of Armenia solely for educational purposes.

This data is unique as the pubs sector in Armenia has not been reasearched so far.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\katec\Thinkful\chap7_data\copy_chap7_data.csv')

In [3]:
df.head(20)

,Timestamp,Age,Gender,Income,Occupation,Fav_Pub,WTS,Freq,Prim_Imp,Sec_Imp,Stratum,Lifestyle,Occasions
0,2017/02/25 10:52:03 PM GMT+4,19,Male,100000.0,Student,Station,2000.0,Several times in a month,Environment,Menu,Capital,Nightlife,Hang outs with friends
1,2017/02/25 10:53:19 PM GMT+4,19,Female,50000.0,Student,Calumet,2000.0,rarely (once two week/or a month),Music,Pricing,Capital,Adventure/traveling/exploring,Hang outs with friends
2,2017/02/25 10:54:05 PM GMT+4,20,Male,100000.0,Student,Liberty,3000.0,rarely (once two week/or a month),Environment,Music,Capital,"Busy(student life, work)",Hang outs with friends
3,2017/02/25 10:55:09 PM GMT+4,18,Male,0.0,Student,Calumet,3000.0,Several times in a month,Environment,Music,Capital,Art,Hang outs with friends
4,2017/02/25 10:55:38 PM GMT+4,19,Female,130000.0,Student + working,Liberty,10000.0,rarely (once two week/or a month),Pricing,Environment,Capital,NaN,Hang outs with friends
5,2017/02/25 10:55:39 PM GMT+4,19,Male,90000.0,Student,Station,2000.0,Several times a week,Environment,Menu,Capital,Adventure/traveling/exploring,Hang outs with friends
6,2017/02/25 10:55:41 PM GMT+4,18,Female,0.0,Student,Irish,1000.0,Several times in a month,Environment,Music,Capital,Art,Hang outs with friends
7,2017/02/25 10:55:45 PM GMT+4,19,Female,0.0,Student,Station,2000.0,Several times in a month,Environment,Pricing,Capital,"Busy(student life, work)",Hang outs with friends
8,2017/02/25 10:56:17 PM GMT+4,19,Male,80000.0,Student + working,I don't like pubs,10000.0,rarely (once two week/or a month),Environment,Music,Capital,Adventure/traveling/exploring,Hang outs with friends
9,2017/02/25 10:56:45 PM GMT+4,19,Male,150000.0,Student,Irish,3000.0,Several times in a month,Environment,Music,Capital,Nightlife,Hang outs with friends
10,2017/02/25 10:56:52 PM GMT+4,20,Female,80000.0,Student,I don't like pubs,3000.0,rarely (once two week/or a month),Environment,Menu,Capital,Art,Special events/parties
11,2017/02/25 10:56:56 PM GMT+4,18,Male,90000.0,Student,Venue,0.0,rarely (once two week/or a month),Environment,Music,Capital,Sport,Hang outs with friends
12,2017/02/25 10:57:00 PM GMT+4,18,Female,0.0,Student,Calumet,2000.0,Several times a week,Environment,Music,Capital,Adventure/traveling/exploring,Hang outs with friends
13,2017/02/25 10:57:58 PM GMT+4,19,Male,200000.0,Working,VOID,5000.0,Several times in a month,Environment,Pricing,Capital,Nightlife,Special events/parties
14,2017/02/25 10:58:12 PM GMT+4,19,Male,120000.0,Student,DAS,2000.0,Several times in a month,Environment,Pricing,Urban,Art,Hang outs with friends
15,2017/02/25 10:58:19 PM GMT+4,17,Female,30000.0,Student,Station,5000.0,Several times in a month,Music,Pricing,Capital,Adventure/traveling/exploring,Hang outs with friends
16,2017/02/25 10:59:18 PM GMT+4,18,Male,0.0,Student,Station,2000.0,Several times in a month,Environment,Music,Capital,Sport,Hang outs with friends
17,2017/02/25 10:59:25 PM GMT+4,19,Female,50000.0,Student,I don't like pubs,8000.0,rarely (once two week/or a month),Environment,Music,Rural,"Sport, art, traveling",Birthdays
18,2017/02/25 10:59:28 PM GMT+4,17,Female,0.0,Student,37 pub,5000.0,rarely (once two week/or a month),Environment,Pricing,Urban,Art,Hang outs with friends
19,2017/02/25 10:59:52 PM GMT+4,19,Female,200000.0,Student + working,I don't like pubs,2000.0,rarely (once two week/or a month),Environment,Music,Urban,Adventure/traveling/exploring,Birthdays

INITIAL impressions based on casual review of data & data description:
A. METHODS: 
1. Data collection via online survey questionnaire -- BIAS towards those who answer online survey questionnaires
2. How did the respondents become aware of the survey? This may create a bias regarding those who responded to survey. Possible sources:
    a. email from the students of the American University of Armenia. From what souce were the email addresses obtained? 
    b. blog: must consider the general topic & intendend audience of the blog.
    c. website: must consider the general topic & intended audience of the website.
    d. advertisement: consider where and when ad would have been seen
    e. flyer: consider where and when flyer would have been seen
    f. pub: consider location and customer base
3. Consider length and form of questions and the requirement to disclose personal information -- BIAS towards those willing to spend time and disclose personal information (age, income)
4. Consider that this may be a survey of "American University of Armenia" students. That would likely be a very specific and unique population in contrast to the rest of Armenian pub-goers. 
5. How was the data from the respondents compiled? 
B. Respondents: 
1. Age - overwhelmingly <25
2. Occupation - overwhelmingly student
C. Analyist
1. Unfamiliar with currency to make any judgement regarding income.
2. Unfamiliar with WTS category.

In [9]:
df.columns.values

array(['Timestamp', 'Age ', 'Gender ', 'Income ', ' Occupation',
       'Fav_Pub', 'WTS', 'Freq', 'Prim_Imp', 'Sec_Imp', 'Stratum',
       'Lifestyle', 'Occasions'], dtype=object)

In [11]:
df['Age '].value_counts()

18    49
19    48
20    31
21    20
17    10
23     5
22     4
26     2
25     2
16     2
41     1
39     1
Name: Age , dtype: int64

In [13]:
df['Gender '].value_counts()

Female    102
Male       73
Name: Gender , dtype: int64

In [16]:
df['Income '].value_counts()

0.0          44
100000.0     14
50000.0      12
80000.0      12
30000.0      11
200000.0      9
60000.0       8
70000.0       7
150000.0      7
120000.0      6
40000.0       6
90000.0       4
20000.0       4
10000.0       3
25000.0       3
250000.0      2
130000.0      2
300000.0      2
900000.0      2
55000.0       2
190000.0      1
400.0         1
240000.0      1
384000.0      1
5000.0        1
180000.0      1
700000.0      1
35000.0       1
75000.0       1
4500000.0     1
170000.0      1
270000.0      1
400000.0      1
140000.0      1
Name: Income , dtype: int64

In [14]:
df[' Occupation'].value_counts()

Student                             122
Student + working                    40
Working                               9
army                                  1
Working                               1
Entrepreneur / Software Engineer      1
CEO                                   1
Name:  Occupation, dtype: int64

In [5]:
df['Occasions'].value_counts()

Hang outs with friends        138
Special events/parties         16
Birthdays                      14
Never                           2
For listening  good music       1
Nowere                          1
chem aycelum                    1
Name: Occasions, dtype: int64

##### More accurate question: What is the most common reason students visit pubs in Armenia? 
The most popular reason the respondents (sample population) to this survey questionnaire visit a pub is to "Hang out with friends".

Sample popuation = overwhelmingly students, age <25, mostly female