In [1]:
import pandas as pd
import numpy as np

In [2]:
nan = np.nan

data = {'HCAHPS Measure ID': ['H_COMP_6_LINEAR_SCORE', 'H_COMP_6_STAR_RATING',
'H_COMP_7_LINEAR_SCORE', 'H_COMP_7_STAR_RATING',
'H_HSP_RATING_LINEAR_SCORE', 'H_HSP_RATING_STAR_RATING',
'H_STAR_RATING'], 
        'Patient Survey Star Rating': [nan, 2, nan, 3, nan, 1, nan], 
        'HCAHPS Linear Mean Value': [87, nan, 90, nan, 76, nan, 71]}
df = pd.DataFrame.from_dict(data, orient='columns')

In [3]:
df

,HCAHPS Measure ID,Patient Survey Star Rating,HCAHPS Linear Mean Value
0,H_COMP_6_LINEAR_SCORE,NaN,87.0
1,H_COMP_6_STAR_RATING,2.0,NaN
2,H_COMP_7_LINEAR_SCORE,NaN,90.0
3,H_COMP_7_STAR_RATING,3.0,NaN
4,H_HSP_RATING_LINEAR_SCORE,NaN,76.0
5,H_HSP_RATING_STAR_RATING,1.0,NaN
6,H_STAR_RATING,NaN,71.0

In [4]:
df = pd.concat([df, pd.DataFrame(columns = ['discharge_LINEAR_SCORE', 'discharge_STAR_RATING',
'transition_LINEAR_SCORE', 'transition_STAR_RATING',
'Overall_LINEAR_SCORE', 'Overall_STAR_RATING',
'Summary_STAR_RATING'])], sort=False)

In [5]:
df

,HCAHPS Measure ID,Patient Survey Star Rating,HCAHPS Linear Mean Value,discharge_LINEAR_SCORE,dscharge_STAR_RATING,transition_LINEAR_SCORE,transition_STAR_RATING,Overall_LINEAR_SCORE,Overall_STAR_RATING,Summary_STAR_RATING
0,H_COMP_6_LINEAR_SCORE,NaN,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,H_COMP_6_STAR_RATING,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,H_COMP_7_LINEAR_SCORE,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,H_COMP_7_STAR_RATING,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,H_HSP_RATING_LINEAR_SCORE,NaN,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,H_HSP_RATING_STAR_RATING,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,H_STAR_RATING,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df['discharge_LINEAR_SCORE'] = df['HCAHPS Linear Mean Value'].where(df['HCAHPS Measure ID'] == 'H_COMP_6_LINEAR_SCORE')

In [7]:
df

,HCAHPS Measure ID,Patient Survey Star Rating,HCAHPS Linear Mean Value,discharge_LINEAR_SCORE,dscharge_STAR_RATING,transition_LINEAR_SCORE,transition_STAR_RATING,Overall_LINEAR_SCORE,Overall_STAR_RATING,Summary_STAR_RATING
0,H_COMP_6_LINEAR_SCORE,NaN,87.0,87.0,NaN,NaN,NaN,NaN,NaN,NaN
1,H_COMP_6_STAR_RATING,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,H_COMP_7_LINEAR_SCORE,NaN,90.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,H_COMP_7_STAR_RATING,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,H_HSP_RATING_LINEAR_SCORE,NaN,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,H_HSP_RATING_STAR_RATING,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,H_STAR_RATING,NaN,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
new_linear = df[['discharge_LINEAR_SCORE', 'transition_LINEAR_SCORE', 
'Overall_LINEAR_SCORE']]

In [13]:
linear = [['H_COMP_6_LINEAR_SCORE', 'H_COMP_7_LINEAR_SCORE', 'H_HSP_RATING_LINEAR_SCORE']]

In [19]:
for column in [new_linear, linear]:
    df[new_linear] = df['HCAHPS Linear Mean Value'].where(df['HCAHPS Measure ID'] == linear)

ValueError: Lengths must match to compare

In [ ]:
df